import { UserModel } from '../interfaces/User.interface';

export const users: UserModel[] = [
  {
    id: '1',
    name: 'Olívia Santos',
    email: 'olivia@gmail.com',
    photo: require('../../assets/users/olivia.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '2',
    name: 'Marcos Antonio',
    email: 'marcos@gmail.com',
    photo: require('../../assets/users/marcos.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '3',
    name: 'João Marcos',
    email: 'joao@gmail.com',
    photo: require('../../assets/users/joao.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '4',
    name: 'Maria',
    email: 'maria@gmail.com',
    photo: require('../../assets/users/maria.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '5',
    name: 'Jéssica',
    email: 'jessica@gmail.com',
    photo: require('../../assets/users/jessica.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '6',
    name: 'Roberto Carlos',
    email: 'roberto@gmail.com',
    photo: require('../../assets/users/roberto.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '7',
    name: 'Pedro Oliveira',
    email: 'pedro@gmail.com',
    photo: require('../../assets/users/pedro.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '8',
    name: 'Raimundo Pereira',
    email: 'raimundo@gmail.com',
    photo: require('../../assets/users/raimundo.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '9',
    name: 'Silvana Silva',
    email: 'silvana@gmail.com',
    photo: require('../../assets/users/silvana.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '10',
    name: 'Vitoria Oliveira',
    email: 'vitoria@gmail.com',
    photo: require('../../assets/users/vitoria.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '11',
    name: 'Marina Santos',
    email: 'marina@gmail.com',
    photo: require('../../assets/users/marina.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '12',
    name: 'Mario Augusto',
    email: 'mario@gmail.com',
    photo: require('../../assets/users/carlos.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '13',
    name: 'Alex Moraes',
    email: 'alex@gmail.com',
    photo: require('../../assets/users/alex.jpg'),
    contacts: () => [],
    chatList: [],
  },
  {
    id: '14',
    name: 'Paulo',
    email: 'paulo@gmail.com',
    photo: require('../../assets/users/paulo.jpg'),
    contacts: () => users.filter(user => user.name !== 'Paulo'),
    chatList: [],
  },
];
