import { UserModel } from '../interfaces/User.interface';
import { chats } from './chats.database';
import { getUUID } from '../functions.util';

export const users: UserModel[] = [
  {
    id: getUUID(),
    name: 'Olívia Santos',
    email: 'olivia@gmail.com',
    photo: require('../../assets/users/olivia.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Marcos Antonio',
    email: 'marcos@gmail.com',
    photo: require('../../assets/users/marcos.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'João Marcos',
    email: 'joao@gmail.com',
    photo: require('../../assets/users/joao.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Maria',
    email: 'maria@gmail.com',
    photo: require('../../assets/users/maria.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Jéssica',
    email: 'jessica@gmail.com',
    photo: require('../../assets/users/jessica.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Roberto Carlos',
    email: 'roberto@gmail.com',
    photo: require('../../assets/users/roberto.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Pedro Oliveira',
    email: 'pedro@gmail.com',
    photo: require('../../assets/users/pedro.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Raimundo Pereira',
    email: 'raimundo@gmail.com',
    photo: require('../../assets/users/raimundo.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Silvana Silva',
    email: 'silvana@gmail.com',
    photo: require('../../assets/users/silvana.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Vitoria Oliveira',
    email: 'vitoria@gmail.com',
    photo: require('../../assets/users/vitoria.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Marina Santos',
    email: 'marina@gmail.com',
    photo: require('../../assets/users/marina.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Mario Augusto',
    email: 'mario@gmail.com',
    photo: require('../../assets/users/carlos.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Alex Moraes',
    email: 'alex@gmail.com',
    photo: require('../../assets/users/alex.jpg'),
    contacts: () => [],
    chatList: () => [],
  },
  {
    id: getUUID(),
    name: 'Paulo',
    email: 'paulo@gmail.com',
    photo: require('../../assets/users/paulo.jpg'),
    contacts: () => users.filter(user => user.name !== users[13].name),
    chatList: () =>
      chats.filter(
        chat => chat.userOne === users[13] || chat.userTwo === users[13],
      ),
  },
];
